backend:
  name: github
  repo: angelakcc-cmyk/astro-sanity-starter  # 替换成你的 GitHub 仓库
  branch: main                                # 主分支，一般是 main

media_folder: "static/images/uploads"        # 上传图片存放路径
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"                  # 页面内容存放路径
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"                  # 博客文章存放路径
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
